apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  name: neo4j-enterprise
  annotations:
    config.kubernetes.io/local-config: "true"
spec:
  info:
    title: Neo4j Enterprise
    version: latest
    actuationTool:
      flavor: Terraform
      version: ">= 1.2"
    description:
      tagline: The world's leading graph database platform
      detailed: |-
        Neo4j Enterprise Edition is a highly scalable, robust graph database designed for mission-critical applications.
        
        Key features include:
        - Clustering for high availability and scalability
        - Advanced security features
        - Monitoring and management tools
        - LDAP/Active Directory integration
        - Hot backups
        - Multi-data center support
    softwareGroups:
      - type: SG_OS
        software:
          - title: ubuntu-2204-jammy
            version: "v20250305"
  content: {}
  interfaces:
    variables:
      - name: project_id
        description: The ID of the project in which to provision resources.
        varType: string
        required: true
      - name: region
        description: The region for the solution to be deployed.
        varType: string
        defaultValue: us-central1
      - name: zone
        description: The zone for the solution to be deployed.
        varType: string
        defaultValue: us-central1-a
      - name: goog_cm_deployment_name
        description: The name of the deployment and VM instances.
        varType: string
        required: true
      - name: source_image
        description: The image name for the disk for the VM instance.
        varType: string
        defaultValue: projects/launcher-public/global/images/neo4j-enterprise-edition-byol-v20250305
      - name: network_name
        description: The network name to attach the VM instance.
        varType: string
        defaultValue: default
      - name: subnetwork_name
        description: The subnetwork name to attach the VM instance.
        varType: string
        defaultValue: ""
      - name: create_network
        description: Whether to create a new network for Neo4j.
        varType: bool
        defaultValue: false
      - name: subnetwork_cidr
        description: The CIDR range for the subnetwork when creating a new network.
        varType: string
        defaultValue: "10.0.0.0/16"
      - name: node_count
        description: Number of Neo4j nodes to deploy (1 for standalone, 3-7 for cluster)
        varType: integer
        defaultValue: 3
      - name: machine_type
        description: The machine type to create, e.g. c3-standard-4
        varType: string
        defaultValue: c3-standard-4
      - name: disk_size
        description: Size of the data disk in GB
        varType: integer
        defaultValue: 100
      - name: admin_password
        description: Password for the Neo4j admin user
        varType: string
        required: true
      - name: install_bloom
        description: Whether to install Neo4j Bloom
        varType: bool
        defaultValue: false
      - name: bloom_license_key
        description: License key for Neo4j Bloom (if installing)
        varType: string
        defaultValue: ""
      - name: firewall_source_range
        description: Source IP ranges for firewall rules
        varType: string
        defaultValue: "0.0.0.0/0"
      - name: license_type
        description: Neo4j license type
        varType: string
        defaultValue: "enterprise"
    outputs:
      - name: neo4j_url
        description: URL to access Neo4j Browser
      - name: neo4j_bolt_url
        description: Bolt URL for connecting to Neo4j
      - name: neo4j_ip_addresses
        description: IP addresses of the Neo4j nodes
      - name: neo4j_instance_names
        description: Names of the Neo4j instances
      - name: neo4j_instance_zones
        description: Zones where Neo4j instances are deployed
      - name: neo4j_instance_machine_types
        description: Machine types of Neo4j instances 