apiVersion: marketplace.cloud.google.com/v1alpha1
kind: Marketplace
metadata:
  name: neo4j-enterprise
  displayName: Neo4j Enterprise
  description: |-
    Neo4j Enterprise Edition is a highly scalable, robust graph database designed for mission-critical applications.
  tagline: The world's leading graph database platform
  url: https://neo4j.com/
  categories:
    - DATABASE
    - BIG_DATA
  icon: https://neo4j.com/wp-content/themes/neo4jweb/assets/images/neo4j-logo-2015.png
  publisher:
    name: Neo4j, Inc.
    url: https://neo4j.com/
  support:
    email: support@neo4j.com
    url: https://support.neo4j.com/
  pricingInfo:
    type: BYOL
    description: |-
      This solution requires a Neo4j Enterprise license. You can use your existing license or contact Neo4j for a new license.
  usageGuidelines:
    - title: Getting Started
      description: |-
        After deployment, you can access Neo4j Browser at http://<external-ip>:7474.
        The default username is 'neo4j' and the password is the one you specified during deployment.
    - title: Connecting to Neo4j
      description: |-
        You can connect to Neo4j using the Bolt protocol at bolt://<external-ip>:7687.
    - title: Cluster Management
      description: |-
        For cluster deployments, Neo4j provides a Causal Clustering architecture that enables high availability and horizontal scalability.
  solutionId: neo4j-enterprise
  solutionType: VM
  solutionDetails:
    version: 1.0.0
    description: |-
      Neo4j Enterprise Edition provides a robust, scalable graph database platform with advanced features for enterprise deployments.
    architecture: |-
      This solution deploys Neo4j Enterprise on Google Compute Engine instances with persistent disk storage.
      For cluster deployments, it configures Neo4j's Causal Clustering for high availability and horizontal scalability.
    securityCompliance:
      - title: Data Encryption
        description: |-
          Data is encrypted at rest using Google Cloud's default encryption.
      - title: Network Security
        description: |-
          Firewall rules are configured to allow only necessary traffic.
    bestPractices:
      - title: Sizing Recommendations
        description: |-
          For production workloads, we recommend using at least 3 nodes for clustering and choosing machine types with at least 8 vCPUs and 32GB RAM.
      - title: Backup Recommendations
        description: |-
          Regular backups are recommended using Neo4j's backup tools or Google Cloud's snapshot capabilities.
  deploymentTiers:
    - name: default
      description: Default deployment configuration
  deploymentParameters:
    - name: project_id
      displayName: Project ID
      description: The GCP project ID where Neo4j will be deployed
      required: true
      type: STRING
    - name: region
      displayName: Region
      description: The GCP region where Neo4j will be deployed
      required: true
      type: STRING
      defaultValue: us-central1
    - name: zone
      displayName: Zone
      description: The GCP zone where Neo4j will be deployed
      required: true
      type: STRING
      defaultValue: us-central1-a
    - name: node_count
      displayName: Number of Nodes
      description: Number of Neo4j nodes to deploy (1 for standalone, 3-7 for cluster)
      required: true
      type: INTEGER
      defaultValue: 3
      validationRegex: ^(1|3|4|5|6|7)$
      validationErrorMessage: Node count must be 1 (standalone) or 3-7 (cluster)
    - name: machine_type
      displayName: Machine Type
      description: GCP machine type for Neo4j nodes
      required: true
      type: STRING
      defaultValue: c3-standard-4
    - name: disk_size
      displayName: Disk Size
      description: Size of the data disk in GB
      required: true
      type: INTEGER
      defaultValue: 100
    - name: admin_password
      displayName: Admin Password
      description: Password for the Neo4j admin user
      required: true
      type: PASSWORD
    - name: install_bloom
      displayName: Install Neo4j Bloom
      description: Whether to install Neo4j Bloom
      required: false
      type: BOOLEAN
      defaultValue: false
    - name: bloom_license_key
      displayName: Bloom License Key
      description: License key for Neo4j Bloom (if installing)
      required: false
      type: STRING
  terraformModuleReference:
    source: ./modules/neo4j 